Repository wecode-bootcamp-korea/40-2nd-DevU-backend, pull requests merged in 2023-01, with the labels that each got.

#6 [40기 박진주] MODIFY : DB - table 추가 및 column 수정
  app.js
  db/migrations/20221226103537_create_books_table.sql
  db/migrations/20221226104118_create_users_table.sql
  db/migrations/20221226104119_create_bookshelves_table.sql
  db/migrations/20221226104121_create_order_items_table.sql
  db/migrations/20230102163643_create_payments_table.sql
Labels: 완료

#7 [40기 박진주] Fixed Database migration files
  db/migrations/20221226103459_create_main_categories_table.sql
  db/migrations/20221226103517_create_sub_categories_table.sql
  db/migrations/20221226103537_create_books_table.sql
  db/migrations/20221226103549_create_book_contents_table.sql
  db/migrations/20221226104117_create_order_statuses_table.sql
  db/migrations/20221226104118_create_users_table.sql
  db/migrations/20221226104119_create_bookshelves_table.sql
  db/migrations/20221226104121_create_order_items_table.sql
  db/migrations/20221226104203_create_reviews_table.sql
  db/migrations/20221226104222_create_carts_table.sql
  db/migrations/20230102163643_create_payments_table.sql
Labels: 멘토 리뷰 요청

#10 [40기 박진주] MODIFY : USERS 테이블 컬럼 POINT 데이터 타입 NOT NULL DEFAULT 100만
  db/migrations/20230105062231_modify_point_column_users.sql
Labels: 리뷰 진행 중

#4 [40기 황정수] ADD: 메인 페이지 구현(전체 상품목록 포함)
  src/controllers/bookController.js
  src/models/bookDao.js
  src/models/dataSource.js
  src/routers/bookRouter.js
  src/routers/index.js
  src/services/bookService.js
  src/utils/error.js
  tests/book.test.js
Labels: 멘토 리뷰 요청

#12 [40기 박진주] 주문 page 조회 및 주문하기 API
  src/controllers/orderController.js
  src/models/orderDao.js
  src/routers/bookRouter.js
  src/routers/bookshelf.router.js
  src/routers/index.js
  src/routers/orderRouter.js
  src/routers/userRouter.js
  src/services/orderService.js
Labels: 멘토 리뷰 요청

#5 [40기 황정수] ADD: 리스트페이지 및 특정 도서 검색 api 구현
  db/migrations/20221226103537_create_books_table.sql
  src/controllers/bookController.js
  src/models/bookDao.js
  src/routers/bookRouter.js
  src/services/bookService.js
Labels: 멘토 리뷰 요청

#8 [40기 황정수] ADD: 리뷰/평점 기능(CRUD) 추가
  .env.sample
  .gitignore
  src/controllers/reviewController.js
  src/models/reviewDao.js
  src/routers/reviewRouter.js
  src/services/reviewService.js
  src/utils/error.js
Labels: 멘토 리뷰 요청
